@startuml "Component Diagram ESL Drone"

component "Screen" as screen
component "Keyboard" as keyboard
component "Joystick" as joystick

interface "Keyboard Keys" as keyboardKeys
interface "Joystick commands" as joystickCommands 

package "Control Interface System" {
    component "Joystick Mapper" as joyStickMapper
    component "Keyboard Mapper" as keyboardMapper
    component "Settings Logic" as settingsLogic
    component "Configurations" as configurations
    component "Settings Visualizer" as settingsVisualizer
    component "Send Serial" as sendserial
    component "CRC" as crc
    component "Read Serial" as readserial

    interface "joystick settings" as joystickSettings
    interface "keyboard settings" as keyboardSetings
    interface "drone commands" as droneCommands
    interface "drone messages" as droneMessages
    interface "drone loggins and settings" as droneLogginsSettings
    interface "interface loggins and settings" as interfaceLogginsSettings

    interface "command settings" as commandSettings
    interface "visualized settings" as visualizedSettings
    database  "System Database" as systemDatabase
}


package "Flight Controller Board" {
component "Send Serial" as sendserialFCB
component "Read Serial" as readserialFCB
component "CRC" as crcFCB
component "Sensors" as sensors
component "Motor control" as motors
component "Stabilization" as stabilization
component "Data packet to command" as packetdrone
component "Data logging" as datalogging
}


joyStickMapper -- joystickSettings
joystickSettings )-- settingsLogic

keyboardMapper -- keyboardSetings
keyboardSetings )-- settingsLogic

settingsLogic -- commandSettings
commandSettings )-- configurations

configurations -right- droneCommands
droneCommands )-- serialProtocol

serialProtocol -left- droneMessages
droneMessages )-left- configurations

configurations -up- droneLogginsSettings
droneLogginsSettings )-up-systemDatabase

systemDatabase -- interfaceLogginsSettings
interfaceLogginsSettings )--settingsVisualizer

settingsVisualizer -right- visualizedSettings
visualizedSettings )-right- screen

keyboard -- keyboardKeys
keyboardKeys )-- keyboardMapper

joystick -- joystickCommands
joystickCommands )--joyStickMapper



serialProtocol .down.> sendserialFCB: RS232

sensors --> sendserialFCB
' readserialFCB-up->crcFCB
' crcFCB-->sendserialFCB
motors <- stabilization
stabilization <- sensors
readserialFCB -up-> packetdrone
packetdrone -> motors
motors --> sendserialFCB
datalogging <-- motors
datalogging <-- sensors

@enduml
